package degoudengids;

public class InterfacePersoonGegevens extends javax.swing.JFrame {
    /**
     * Met deze klasse kunnen de variabelen van een persoon object worden bekeken en veranderd. De veranderingen worden ook gelijk doorgevoerd in de database.
     */

    Database database;
    Medewerker persoon;
    int evenementCode;
    // Variables declaration - do not modify                     
    private javax.swing.JLabel achternaamLabel;
    private javax.swing.JTextField achternaamVak;
    private javax.swing.JLabel cursusLabel;
    private javax.swing.JTextField cursusVak;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailVak;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idVak;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel naamLabel;
    private javax.swing.JTextField naamVak;
    private javax.swing.JButton opslaanKnop;
    private javax.swing.JButton sluitKnop;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JLabel telefoonnummerLabel2;
    private javax.swing.JLabel telefoonnummerLabel7;
    private javax.swing.JTextField datumVak;
    /**
     * Creates new form InterfacePersoonGegevens
     */

    public InterfacePersoonGegevens(Database database, Medewerker selected) {
        // Koppelen van de doorgegeven data.
        this.database = database;
        this.persoon = selected;

        initComponents();

        setGegevens();

        // Venster op de juiste manier laten verschijnen
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setTitle("Persoon gegevens");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telefoonnummerLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        telefoonnummerLabel7 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        naamLabel = new javax.swing.JLabel();
        achternaamLabel = new javax.swing.JLabel();
        idVak = new javax.swing.JTextField();
        naamVak = new javax.swing.JTextField();
        achternaamVak = new javax.swing.JTextField();
        datumLabel = new javax.swing.JLabel();
        datumVak = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailVak = new javax.swing.JTextField();
        sluitKnop = new javax.swing.JButton();
        opslaanKnop = new javax.swing.JButton();
        cursusVak = new javax.swing.JTextField();
        cursusLabel = new javax.swing.JLabel();

        telefoonnummerLabel2.setText("Datum in dienst");

        jTextField6.setMinimumSize(new java.awt.Dimension(200, 28));
        jTextField6.setPreferredSize(new java.awt.Dimension(200, 28));

        telefoonnummerLabel7.setText("Datum in dienst");

        jTextField11.setMinimumSize(new java.awt.Dimension(200, 28));
        jTextField11.setPreferredSize(new java.awt.Dimension(200, 28));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        idLabel.setText("ID");

        naamLabel.setText("Voornaam");

        achternaamLabel.setText("Achternaam");

        idVak.setEditable(false);
        idVak.setMinimumSize(new java.awt.Dimension(200, 28));
        idVak.setPreferredSize(new java.awt.Dimension(200, 28));

        naamVak.setMinimumSize(new java.awt.Dimension(200, 28));
        naamVak.setPreferredSize(new java.awt.Dimension(200, 28));

        achternaamVak.setMinimumSize(new java.awt.Dimension(200, 28));
        achternaamVak.setPreferredSize(new java.awt.Dimension(200, 28));

        datumLabel.setText("Datum in dienst");

        datumVak.setMinimumSize(new java.awt.Dimension(200, 28));
        datumVak.setPreferredSize(new java.awt.Dimension(200, 28));

        emailLabel.setText("Email adres");

        emailVak.setMinimumSize(new java.awt.Dimension(200, 28));
        emailVak.setPreferredSize(new java.awt.Dimension(200, 28));

        sluitKnop.setText("Sluiten");
        sluitKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sluitKnopActionPerformed(evt);
            }
        });

        opslaanKnop.setText("Opslaan");
        opslaanKnop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opslaanKnopActionPerformed(evt);
            }
        });

        cursusVak.setEditable(false);
        cursusVak.setMinimumSize(new java.awt.Dimension(200, 28));
        cursusVak.setPreferredSize(new java.awt.Dimension(200, 28));

        cursusLabel.setText("Gevolgde cursus");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(naamLabel)
                                                        .addComponent(idLabel)
                                                        .addComponent(achternaamLabel)
                                                        .addComponent(datumLabel)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(emailLabel))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(cursusLabel)))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cursusVak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(achternaamVak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(naamVak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(idVak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(datumVak, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(emailVak, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(opslaanKnop)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(sluitKnop)))))
                                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(idLabel)
                                        .addComponent(idVak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(naamLabel)
                                        .addComponent(naamVak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(achternaamLabel)
                                        .addComponent(achternaamVak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(datumLabel)
                                        .addComponent(datumVak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(emailLabel)
                                        .addComponent(emailVak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cursusVak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cursusLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(opslaanKnop)
                                        .addComponent(sluitKnop))
                                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Knop voor het afsluiten van het venster.
     *
     * @param evt
     */
    private void sluitKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sluitKnopActionPerformed
        this.dispose();
    }//GEN-LAST:event_sluitKnopActionPerformed

    /**
     * Deze methode word gebruikt om persoonsgegevens die in de TextField worden ingevuld op te slaan. Hiermee word zowel de klasse persoon, als de inforamtie in de database aangepast.
     * Met die informatie word dan vanuit de klasse database een query uitgevoerd naar de werkelijke database om deze informatie aan te pasen.
     * Vervolgend word alle informatie uit TextFields gehaald. Hiermee word het persoon object veranderd.
     * Vervolgens word dit persoon object megegeven aan een methode in de klasse Database die deze veranderingen doorvoerd in de database zelf.
     * Hierna wordt het venster gesloten.
     *
     * @param evt
     */
    private void opslaanKnopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opslaanKnopActionPerformed
        persoon.setNaam(naamVak.getText());
        persoon.setAchterNaam(achternaamVak.getText());
        persoon.setEmail(emailVak.getText());
        persoon.setDatum_in_dienst(datumVak.getText());

        database.aanpassenPersoonGegevens(persoon);
        this.dispose();
    }//GEN-LAST:event_opslaanKnopActionPerformed

    /**
     * Deze methode vult de TextFields met variabelen uit het persoon object dat word megegeven uit de opstart klasse.
     * Deze methode word aangeroepen in de opstart Klasse.
     */
    public void setGegevens() {
        if (persoon == null) {
            System.out.println("Persoon is null");
        } else {
            idVak.setText(String.valueOf(persoon.getMedw_nr()));
            naamVak.setText(persoon.getNaam());
            achternaamVak.setText(persoon.getAchterNaam());
            datumVak.setText(persoon.getDatum_in_dienst());
            emailVak.setText(persoon.getEmail());
            cursusVak.setText(persoon.getCursus_naam());
        }
    }
    // End of variables declaration                   
}
